### ISSUE TITLE
Webrtc callbacks not working when come from notification.

### ISSUE THREAD

**Issue by vivekf16** [QuickBlox/quickblox-flutter-sdk#35]
When app is open Callbacks of webrtc are working fine. But after notification arrived when on click we init webrtc and set callbacks its not giving callback.

quickblox Flutter version ^0.5.2-beta

**Comment by ghost** [comment]
Hello,

This is Nikolay from QuickBlox support.

Please clarify if the issue is that a callback is not received after you click on a notification.

Unfortunately, there is no method for click events for notifications in our Flutter SDK. 

Requests like that are not processed by our server and are not related to the server-side implementation.

The handling of click events and interactions with push notifications is up to the client-side. You may try implementing such a feature on your end.

These links can be helpful:
https://stackoverflow.com/questions/48403786/how-to-open-particular-screen-on-clicking-on-push-notification-for-flutter
https://flutteragency.com/how-to-open-particular-screen-on-clicking-on-push-notification-for-flutter/
https://medium.com/@abumuhab/flutter-notifications-routing-to-specific-screens-on-notification-click-85fe3c9b5ba9

Also, we suggest upgrading the QuickBlox Flutter SDK to the latest version:
[https://pub.dev/packages/quickblox_sdk/versions/0.6.1-beta](https://pub.dev/packages/quickblox_sdk/versions/0.6.1-beta)

**Comment by vivekf16** [comment]
@QB-nikolay-zolotarov  

I have integrated my own notification module in Flutter.

**Comment by suhailzoft** [comment]
@Anonymousthe1 Was your issue fixed?

**Comment by vivekf16** [comment]
@QB-nikolay-zolotarov  

Starting integration will update you soon.

**Comment by vivekf16** [comment]
@QB-nikolay-zolotarov  

I have tested using the latest **0.6.2-beta** seems callback which was working in the previous lib **0.6.1** stopped in this new version.

Webrtc callbacks in after coming from the killed state are also not working.

**Comment by ghost** [comment]
@Anonymousthe1 
The issue is being investigated.

Once there is any news, I will let you know.

**Comment by ghost** [comment]
@suhail-zartek @Anonymousthe1
Please double-check the application workflow:

    open app (from background or icon)
    settings → init credentials
    auth → login
    chat → connect, subscribe to events
    webrtc → init, subscribe to events
    receive the call (or another) event
    app goes to background
    webrtc → unsubscribe, release
    chat → unsubscribe, disconnect

If you follow this order, the call (and another) event should be received correctly.
