### ISSUE TITLE
Can't build in ios

### ISSUE THREAD

**Issue by TungWang** [QuickBlox/quickblox-flutter-sdk#39]
I'am trying to build an app with quickblox, but i receive error below:

```
[!] CocoaPods could not find compatible versions for pod "quickblox_sdk":
  In Podfile:
    quickblox_sdk (from `.symlinks/plugins/quickblox_sdk/ios`)

Specs satisfying the `quickblox_sdk (from `.symlinks/plugins/quickblox_sdk/ios`)` dependency were found, but they required a higher minimum deployment target.
```

Please help me!

**Comment by ghost** [comment]
@TungWang Hello,

This is Nikolay from QuickBlox support.

Please let me know if you followed these instructions on how to install the QuickBlox Flutter SDK:
[https://docs.quickblox.com/docs/flutter-quick-start](https://docs.quickblox.com/docs/flutter-quick-start)

Also, please make sure that the iOS version in your project’s Podfile is not lower than 13.0 when installing SDK.

Additionally, please check if the string where the iOS deployment target is defined is not commented.

If the issue is still observed, please provide me with your pod file and the screenshot of the error you receive after the update.
Also, please provide the following points:
1. Version of QuickBlox Flutter SDK.
2. iOS version.
3. Devices in use.
4. Flutter version.
5. Dart version.

**Comment by TungWang** [comment]
I'm sorry. I tried to build an app in iOS 12, so it's not an issue.

**Comment by ghost** [comment]
@TungWang Thank you for notifying me.

The issue is being closed.

**Comment by jaymes15** [comment]
@QB-nikolay-zolotarov I am also getting this issue.

- Version of QuickBlox Flutter SDK => quickblox_sdk: ^0.6.4-beta.
- iOS version => 13.0.
- Devices in use => iOS simulator iPhone 12 pro max.
 - Flutter version =>  2.8.1 (As of now this is the latest flutter version)
 - Dart version => 2.15.1.

**Comment by jaymes15** [comment]
here is my Podfile:

<img width="1792" alt="Screen Shot 2022-01-06 at 2 56 36 PM" src="https://user-images.githubusercontent.com/46538679/148393692-77e38b2f-c228-41ff-93a3-6304ef57c9b0.png">

**Comment by jaymes15** [comment]
here is my pub_spec.yml file:
<img width="222" alt="Screen Shot 2022-01-06 at 2 58 39 PM" src="https://user-images.githubusercontent.com/46538679/148393981-32638b7b-f7a4-426a-9a1c-e5cfada69e28.png">

**Comment by jaymes15** [comment]
Please help me!

**Comment by jaymes15** [comment]
<img width="348" alt="Screen Shot 2022-01-06 at 3 07 18 PM" src="https://user-images.githubusercontent.com/46538679/148395185-f5a90636-fdf6-4e7c-9703-09ce7c6b2adb.png">

**Comment by ghost** [comment]
@jaymes15 Thank you for the detailed information.
Please specify the current error. You may provide a screenshot of full logs.
