### ISSUE TITLE
Some times local video showing as black screen

### ISSUE THREAD

**Issue by suhailzoft** [QuickBlox/quickblox-flutter-sdk#42]
When i try to trigger a call to iOS device, local video become black screen. But, remote video working fine.Also, local video and remote video from the iOS device showing well in the web where we initiated the call.It's not happening every time.Also,It's working well in android devices.Please help me to solve this issue ASAP.

**Comment by ghost** [comment]
@suhailzoft Hello,

This is Nikolay from QuickBlox support.

According to my check, you already submitted a ticket and the issue is being investigated.

Once there is any news, we will let you know.

**Comment by QB-maksym-pidhorbunskyi** [comment]
@suhailzoft Hello,

This is Maksym from the QuickBlox support.

According to the provided details in the ticket that you submitted via [Help Center](https://help.quickblox.com/conversation/new) and code review by our Flutter developer on a paid basis, the root reason of the issue has been found.

In general, the issue relates to wrong logic for calling Flutter SDK methods.
The video views (remote and local) have controllers which render (play) the video tracks. 
In your implementation the play method was called earlier than controllers are ready. It’s producing the issue which that you described.

Wrong workflow:
- user accepts a call
- start call screen
- video view starts but 
hasn’t complete a controller. Call back isn’t called
- received video track
- start to render (call play method) a video track
- controller isn’t complete and user sees the black screen.

Correct workflow:
- user accepts a call
- start call screen
- video view starts and controller 
has completed. Call back is called
- received video track
- start to render (call play method) a video track
- a controller is complete and a user see the local video

Additionally, once the call ends, you need to call QB.webrtc.release(); in order to release a resource.
release() method should be called when a video track is no more valid. If you don't call this method, you will get a memory leak.

The detailed workflow of video calling can be found in [our official documentation](https://docs.quickblox.com/docs/flutter-video-calling#resources)

We consider this issue as resolved and move it to Closed.
