### ISSUE TITLE
Insufficient privileges to perform this request: Your user is not in occupants list of the dialog

### ISSUE THREAD

**Issue by AnsarILeaf** [QuickBlox/quickblox-flutter-sdk#45]
This issue can be reproduced when

1. Login two Quickblox users one after another. (First user does not have any issues)
2. while we login second time with another user this error occurs
3. Dialogs list and message list are coming as normal
4. Issue happens when sending a message
5. Logout method is called successfully 
6. When clearing all app data and login as second user everything works normal

Following is the console log

xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Insufficient privileges to perform this request: Your user is not in occupants list of the dialog</text></error></presence>
W/System.err( 8521): org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPPError: forbidden - auth
W/System.err( 8521): 	at org.jivesoftware.smack.PacketCollector.nextResultOrThrow(Unknown Source:9)
W/System.err( 8521): 	at org.jivesoftware.smackx.muc.MultiUserChat.enter(Unknown Source:245)
W/System.err( 8521): 	at org.jivesoftware.smackx.muc.MultiUserChat.join(Unknown Source:8)
W/System.err( 8521): 	at com.quickblox.chat.QBGroupChat.join(Unknown Source:92)
W/System.err( 8521): 	at com.quickblox.chat.model.QBChatDialog.join(Unknown Source:14)
W/System.err( 8521): 	at com.quickblox.quickblox_sdk.chat.ChatModule$JoinPublicChatJob.doInBackground(ChatModule.java:1206)
W/System.err( 8521): 	at com.quickblox.quickblox_sdk.chat.ChatModule$JoinPublicChatJob.doInBackground(ChatModule.java:1181)
W/System.err( 8521): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
W/System.err( 8521): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err( 8521): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
W/System.err( 8521): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 8521): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 8521): 	at java.lang.Thread.run(Thread.java:919)

**Comment by ghost** [comment]
@AnsarILeaf Hello,

This is Nikolay from QuickBlox support.

It is not possible to be logged in for 2 users at the same time. Please clarify if you called the logout method before the second user logged in.

To investigate the issue further, we need the following points:
1. Please provide me with more detailed information about your application workflow.
2. Version of QuickBlox Flutter SDK.
Please make sure that you use the latest version of the QuickBlox Flutter SDK:
[https://pub.dev/packages/quickblox_sdk/changelog#064-beta](https://pub.dev/packages/quickblox_sdk/changelog#064-beta)
3. Platform where the issue is reproduced (Android, iOS, or both).
4. Version of the platform (e.g. Android 11, iOS 13).
5. Flutter version.
6. Please provide me with more detailed instructions on how to reproduce the issue on our end.
7. Please provide full REST + XMPP logs as an attachment in .txt format. 
You can find out how to gather logs here: [https://docs.quickblox.com/docs/flutter-setup#enable-logging](https://docs.quickblox.com/docs/flutter-setup#enable-logging)
8. Please specify the dialog type. Make sure that the user is present in the occupant list.

**Comment by AnsarILeaf** [comment]
@QB-nikolay-zolotarov  Thanks for the reply.

Two users are not used same time. After calling the logout method only we are using a second user.

1. Create user/ login user  ->  group chat is used for chatting. 
    After logout login to another user -> while sending a message by the second user the issue arrises
2. quickblox_sdk: 0.6.3-beta
3. Issue is there on both iOS and Android
4. Android 10, iOS 15.0
5. Flutter version 2.8.1
6. Needs 2 users, create necessary group chats for testing (with other users). Log in with one user, send a message, logout
    Login second user send message to any user
7. 
[log.txt](https://github.com/QuickBlox/quickblox-flutter-sdk/files/7742707/log.txt)
8. Group

**Comment by ghost** [comment]
@AnsarILeaf Thank you for your reply.

Please provide logs from application start till request and "wrong" response (error).

Here is a guide: [https://docs.quickblox.com/docs/flutter-setup#enable-logging](https://docs.quickblox.com/docs/flutter-setup#enable-logging)
