### ISSUE TITLE
Asset validation failed (90482) Invalid Executable. The executable 'Runner.app/Frameworks/QuickbloxWebRTC.framework/QuickbloxWebRTC' contains bitcode

### ISSUE THREAD

**Issue by kariot** [QuickBlox/quickblox-flutter-sdk#84]
Getting this error message when trying to upload an App using this package to the App Store.
<img width="742" alt="Screenshot 2024-09-25 at 11 58 37 AM" src="https://github.com/user-attachments/assets/23d6a18e-ea16-4257-b4a9-614964d706fb">

**Comment by IlliaChemolosov** [comment]
@kariot Hello!

:rotating_light: If you’re seeing this error:
“Invalid Executable. Executable App.app/Frameworks/QuickbloxWebRTC.framework/QuickbloxWebRTC contains bitcode” after updating to Xcode 16, it’s probably due to outdated libraries.

:arrows_counterclockwise: Fix: Update your libraries! Make sure you’re using QuickbloxWebRTC v3.0.0+.

**CocoaPods Users (Flutter/React Native)**

CocoaPods might install an older version due to iOS version settings. For QuickbloxWebRTC v3.1.0, iOS 13.0+ is required. Check your Podfile and set iOS 13+ if needed. Don’t forget to update your project/target settings in Xcode.

:bulb: Alternative: Downgrade Xcode (not recommended). Best to keep everything up-to-date for compatibility.
